//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibrary.Core.Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictBookGenre
    {
        public DictBookGenre()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int BookGenreId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
